parameters:
#    cl_belgian_national_number.example.class: CL\BelgianNationalNumberBundle\Example

services:
    validator.belgian_national_number:
        class: CL\BelgianNationalNumberBundle\Validator\Constraint\BelgianNationalNumberValidator
        tags:
            - { name: validator.constraint_validator, alias: belgian_national_number }
